version: '3.7'

services:

  mongo-express:
    image: mongo-express:0.49
    restart: always
    container_name: mongo_ui
    ports:
      - 8082:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    links:
      - mongodb:mongo
    depends_on:
      - mongodb