version: "3.0"

services:
  example:
    image: ubuntu
    command: bash -c "for i in `seq 1 1000`; do echo 'the a example container '$i; sleep 1; done;"
    logging:
      driver: "gelf"
      options:
        gelf-address: 'udp://127.0.0.1:12201'
        tag: "example"
