version: '3.7'

services:
  elasticsearch:
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true

  elasticsearch_2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
    #    volumes:
    #      - ./es_data:/usr/share/elasticsearch/data
    #      - ./es_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cat/health?h=status | grep 'green'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "9201:9200"

  elasticsearch_3:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
    #    volumes:
    #      - ./es_data:/usr/share/elasticsearch/data
    #      - ./es_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cat/health?h=status | grep 'green'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "9202:9200"