version: "3.0"

services:
  example:
    image: alpine
    command: "echo 'the a example container'"
    logging:
      driver: "gelf"
      options:
        gelf-address: 'udp://127.0.0.1:12201'
        tag: "example"
