version: '3'

services:

  mongo:
    image: mongo:3.6
    healthcheck:
      test: ["CMD", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
  #    volumes:
  #      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express:0.49
    restart: always
    working_dir: /app
    ports:
      - 8082:8081
#    healthcheck:
#      test: ["CMD-SHELL", "apk add curl && curl -f http://localhost:8081"]
#      interval: 10s
#      timeout: 10s
#      retries: 5
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: on-failure

  graylog:
    depends_on:
      - mongo
    environment:
      - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog