version: '3.7'

services:
  mongodb:
    image: mongo:3.6
    healthcheck:
      test: ["CMD", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
#    volumes:
#      - ./mongo_data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
#    volumes:
#      - ./es_data:/usr/share/elasticsearch/data
#      - ./es_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:9200/_cat/health?h=status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  graylog:
    image: graylog/graylog:3.0
#    volumes:
#      - ./graylog_data:/usr/share/graylog/data/journal
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9001/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9001:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.7.2
#    volumes:
#      - ./kibana_data/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s