version: '3'

services:

  mongodb:
    image: mongo:3.6
    healthcheck:
      test: ["CMD", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 5
  #    volumes:
  #      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8082:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 70s
      timeout: 50s
      retries: 5
    links:
      - mongodb:mongo
    depends_on:
      - mongodb

  graylog:
    depends_on:
      - mongodb
    links:
      - mongodb:mongo
    environment:
      - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog